// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace SampleDAL
{
    // Customer
    public partial class SalesLT_Customer
    {
        public int CustomerId { get; set; } // CustomerID (Primary key)
        public bool NameStyle { get; set; } // NameStyle
        public string Title { get; set; } // Title (length: 8)
        public string FirstName { get; set; } // FirstName (length: 50)
        public string MiddleName { get; set; } // MiddleName (length: 50)
        public string LastName { get; set; } // LastName (length: 50)
        public string Suffix { get; set; } // Suffix (length: 10)
        public string CompanyName { get; set; } // CompanyName (length: 128)
        public string SalesPerson { get; set; } // SalesPerson (length: 256)
        public string EmailAddress { get; set; } // EmailAddress (length: 50)
        public string Phone { get; set; } // Phone (length: 25)
        public string PasswordHash { get; set; } // PasswordHash (length: 128)
        public string PasswordSalt { get; set; } // PasswordSalt (length: 10)
        public Guid Rowguid { get; set; } // rowguid
        public DateTime ModifiedDate { get; set; } // ModifiedDate

        // Reverse navigation

        /// <summary>
        /// Child SalesLT_CustomerAddresses where [CustomerAddress].[CustomerID] point to this entity (FK_CustomerAddress_Customer_CustomerID)
        /// </summary>
        public ICollection<SalesLT_CustomerAddress> SalesLT_CustomerAddresses { get; set; } // CustomerAddress.FK_CustomerAddress_Customer_CustomerID

        /// <summary>
        /// Child SalesLT_SalesOrderHeaders where [SalesOrderHeader].[CustomerID] point to this entity (FK_SalesOrderHeader_Customer_CustomerID)
        /// </summary>
        public ICollection<SalesLT_SalesOrderHeader> SalesLT_SalesOrderHeaders { get; set; } // SalesOrderHeader.FK_SalesOrderHeader_Customer_CustomerID

        public SalesLT_Customer()
        {
            SalesLT_CustomerAddresses = new List<SalesLT_CustomerAddress>();
            SalesLT_SalesOrderHeaders = new List<SalesLT_SalesOrderHeader>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
