// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace SampleDAL
{
    // Product
    public class SalesLT_Product
    {
        public int ProductId { get; set; } // ProductID (Primary key)
        public string Name { get; set; } // Name (length: 50)
        public string ProductNumber { get; set; } // ProductNumber (length: 25)
        public string Color { get; set; } // Color (length: 15)
        public decimal StandardCost { get; set; } // StandardCost
        public decimal ListPrice { get; set; } // ListPrice
        public string Size { get; set; } // Size (length: 5)
        public decimal? Weight { get; set; } // Weight
        public int? ProductCategoryId { get; set; } // ProductCategoryID
        public int? ProductModelId { get; set; } // ProductModelID
        public DateTime SellStartDate { get; set; } // SellStartDate
        public DateTime? SellEndDate { get; set; } // SellEndDate
        public DateTime? DiscontinuedDate { get; set; } // DiscontinuedDate
        public byte[] ThumbNailPhoto { get; set; } // ThumbNailPhoto
        public string ThumbnailPhotoFileName { get; set; } // ThumbnailPhotoFileName (length: 50)
        public Guid Rowguid { get; set; } // rowguid
        public DateTime ModifiedDate { get; set; } // ModifiedDate

        // Reverse navigation

        /// <summary>
        /// Child SalesLT_SalesOrderDetails where [SalesOrderDetail].[ProductID] point to this entity (FK_SalesOrderDetail_Product_ProductID)
        /// </summary>
        public ICollection<SalesLT_SalesOrderDetail> SalesLT_SalesOrderDetails { get; set; } // SalesOrderDetail.FK_SalesOrderDetail_Product_ProductID

        // Foreign keys

        /// <summary>
        /// Parent SalesLT_ProductCategory pointed by [Product].([ProductCategoryId]) (FK_Product_ProductCategory_ProductCategoryID)
        /// </summary>
        public SalesLT_ProductCategory SalesLT_ProductCategory { get; set; } // FK_Product_ProductCategory_ProductCategoryID

        /// <summary>
        /// Parent SalesLT_ProductModel pointed by [Product].([ProductModelId]) (FK_Product_ProductModel_ProductModelID)
        /// </summary>
        public SalesLT_ProductModel SalesLT_ProductModel { get; set; } // FK_Product_ProductModel_ProductModelID

        public SalesLT_Product()
        {
            Rowguid = Guid.NewGuid();
            ModifiedDate = DateTime.Now;
            SalesLT_SalesOrderDetails = new List<SalesLT_SalesOrderDetail>();
        }
    }

}
// </auto-generated>
