// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace SampleDAL
{
    // SalesOrderHeader
    public partial class SalesLT_SalesOrderHeader
    {
        public int SalesOrderId { get; set; } // SalesOrderID (Primary key)
        public byte RevisionNumber { get; set; } // RevisionNumber
        public DateTime OrderDate { get; set; } // OrderDate
        public DateTime DueDate { get; set; } // DueDate
        public DateTime? ShipDate { get; set; } // ShipDate
        public byte Status { get; set; } // Status
        public bool OnlineOrderFlag { get; set; } // OnlineOrderFlag
        public string SalesOrderNumber { get; set; } // SalesOrderNumber (length: 25)
        public string PurchaseOrderNumber { get; set; } // PurchaseOrderNumber (length: 25)
        public string AccountNumber { get; set; } // AccountNumber (length: 15)
        public int CustomerId { get; set; } // CustomerID
        public int? ShipToAddressId { get; set; } // ShipToAddressID
        public int? BillToAddressId { get; set; } // BillToAddressID
        public string ShipMethod { get; set; } // ShipMethod (length: 50)
        public string CreditCardApprovalCode { get; set; } // CreditCardApprovalCode (length: 15)
        public decimal SubTotal { get; set; } // SubTotal
        public decimal TaxAmt { get; set; } // TaxAmt
        public decimal Freight { get; set; } // Freight
        public decimal TotalDue { get; set; } // TotalDue
        public string Comment { get; set; } // Comment
        public Guid Rowguid { get; set; } // rowguid
        public DateTime ModifiedDate { get; set; } // ModifiedDate

        // Reverse navigation

        /// <summary>
        /// Child SalesLT_SalesOrderDetails where [SalesOrderDetail].[SalesOrderID] point to this entity (FK_SalesOrderDetail_SalesOrderHeader_SalesOrderID)
        /// </summary>
        public virtual ICollection<SalesLT_SalesOrderDetail> SalesLT_SalesOrderDetails { get; set; } // SalesOrderDetail.FK_SalesOrderDetail_SalesOrderHeader_SalesOrderID

        // Foreign keys

        /// <summary>
        /// Parent SalesLT_Address pointed by [SalesOrderHeader].([BillToAddressId]) (FK_SalesOrderHeader_Address_BillTo_AddressID)
        /// </summary>
        public virtual SalesLT_Address BillToAddress { get; set; } // FK_SalesOrderHeader_Address_BillTo_AddressID

        /// <summary>
        /// Parent SalesLT_Address pointed by [SalesOrderHeader].([ShipToAddressId]) (FK_SalesOrderHeader_Address_ShipTo_AddressID)
        /// </summary>
        public virtual SalesLT_Address ShipToAddress { get; set; } // FK_SalesOrderHeader_Address_ShipTo_AddressID

        /// <summary>
        /// Parent SalesLT_Customer pointed by [SalesOrderHeader].([CustomerId]) (FK_SalesOrderHeader_Customer_CustomerID)
        /// </summary>
        public virtual SalesLT_Customer SalesLT_Customer { get; set; } // FK_SalesOrderHeader_Customer_CustomerID

        public SalesLT_SalesOrderHeader()
        {
            SalesLT_SalesOrderDetails = new List<SalesLT_SalesOrderDetail>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
