// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace SampleDAL
{
    // ProductModel
    public class SalesLT_ProductModel
    {
        public int ProductModelId { get; set; } // ProductModelID (Primary key)
        public string Name { get; set; } // Name (length: 50)
        public string CatalogDescription { get; set; } // CatalogDescription
        public Guid Rowguid { get; set; } // rowguid
        public DateTime ModifiedDate { get; set; } // ModifiedDate

        // Reverse navigation

        /// <summary>
        /// Child SalesLT_Products where [Product].[ProductModelID] point to this entity (FK_Product_ProductModel_ProductModelID)
        /// </summary>
        public ICollection<SalesLT_Product> SalesLT_Products { get; set; } // Product.FK_Product_ProductModel_ProductModelID

        /// <summary>
        /// Child SalesLT_ProductModelProductDescriptions where [ProductModelProductDescription].[ProductModelID] point to this entity (FK_ProductModelProductDescription_ProductModel_ProductModelID)
        /// </summary>
        public ICollection<SalesLT_ProductModelProductDescription> SalesLT_ProductModelProductDescriptions { get; set; } // ProductModelProductDescription.FK_ProductModelProductDescription_ProductModel_ProductModelID

        public SalesLT_ProductModel()
        {
            Rowguid = Guid.NewGuid();
            ModifiedDate = DateTime.Now;
            SalesLT_Products = new List<SalesLT_Product>();
            SalesLT_ProductModelProductDescriptions = new List<SalesLT_ProductModelProductDescription>();
        }
    }

}
// </auto-generated>
