// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace SampleDAL
{
    // ProductCategory
    public partial class SalesLT_ProductCategory
    {
        public int ProductCategoryId { get; set; } // ProductCategoryID (Primary key)
        public int? ParentProductCategoryId { get; set; } // ParentProductCategoryID
        public string Name { get; set; } // Name (length: 50)
        public Guid Rowguid { get; set; } // rowguid
        public DateTime ModifiedDate { get; set; } // ModifiedDate

        // Reverse navigation

        /// <summary>
        /// Child SalesLT_Products where [Product].[ProductCategoryID] point to this entity (FK_Product_ProductCategory_ProductCategoryID)
        /// </summary>
        public ICollection<SalesLT_Product> SalesLT_Products { get; set; } // Product.FK_Product_ProductCategory_ProductCategoryID

        /// <summary>
        /// Child SalesLT_ProductCategories where [ProductCategory].[ParentProductCategoryID] point to this entity (FK_ProductCategory_ProductCategory_ParentProductCategoryID_ProductCategoryID)
        /// </summary>
        public ICollection<SalesLT_ProductCategory> SalesLT_ProductCategories { get; set; } // ProductCategory.FK_ProductCategory_ProductCategory_ParentProductCategoryID_ProductCategoryID

        // Foreign keys

        /// <summary>
        /// Parent SalesLT_ProductCategory pointed by [ProductCategory].([ParentProductCategoryId]) (FK_ProductCategory_ProductCategory_ParentProductCategoryID_ProductCategoryID)
        /// </summary>
        public SalesLT_ProductCategory ParentProductCategory { get; set; } // FK_ProductCategory_ProductCategory_ParentProductCategoryID_ProductCategoryID

        public SalesLT_ProductCategory()
        {
            SalesLT_Products = new List<SalesLT_Product>();
            SalesLT_ProductCategories = new List<SalesLT_ProductCategory>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
