// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace SampleDAL
{
    // CustomerAddress
    public partial class SalesLT_CustomerAddress
    {
        public int CustomerId { get; set; } // CustomerID (Primary key)
        public int AddressId { get; set; } // AddressID (Primary key)
        public string AddressType { get; set; } // AddressType (length: 50)
        public Guid Rowguid { get; set; } // rowguid
        public DateTime ModifiedDate { get; set; } // ModifiedDate

        // Foreign keys

        /// <summary>
        /// Parent SalesLT_Address pointed by [CustomerAddress].([AddressId]) (FK_CustomerAddress_Address_AddressID)
        /// </summary>
        public SalesLT_Address SalesLT_Address { get; set; } // FK_CustomerAddress_Address_AddressID

        /// <summary>
        /// Parent SalesLT_Customer pointed by [CustomerAddress].([CustomerId]) (FK_CustomerAddress_Customer_CustomerID)
        /// </summary>
        public SalesLT_Customer SalesLT_Customer { get; set; } // FK_CustomerAddress_Customer_CustomerID

        public SalesLT_CustomerAddress()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
