// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace SampleDAL
{
    // SalesOrderDetail
    public partial class SalesLT_SalesOrderDetail
    {
        public int SalesOrderId { get; set; } // SalesOrderID (Primary key)
        public int SalesOrderDetailId { get; set; } // SalesOrderDetailID (Primary key)
        public short OrderQty { get; set; } // OrderQty
        public int ProductId { get; set; } // ProductID
        public decimal UnitPrice { get; set; } // UnitPrice
        public decimal UnitPriceDiscount { get; set; } // UnitPriceDiscount
        public decimal LineTotal { get; set; } // LineTotal
        public Guid Rowguid { get; set; } // rowguid
        public DateTime ModifiedDate { get; set; } // ModifiedDate

        // Foreign keys

        /// <summary>
        /// Parent SalesLT_Product pointed by [SalesOrderDetail].([ProductId]) (FK_SalesOrderDetail_Product_ProductID)
        /// </summary>
        public SalesLT_Product SalesLT_Product { get; set; } // FK_SalesOrderDetail_Product_ProductID

        /// <summary>
        /// Parent SalesLT_SalesOrderHeader pointed by [SalesOrderDetail].([SalesOrderId]) (FK_SalesOrderDetail_SalesOrderHeader_SalesOrderID)
        /// </summary>
        public SalesLT_SalesOrderHeader SalesLT_SalesOrderHeader { get; set; } // FK_SalesOrderDetail_SalesOrderHeader_SalesOrderID

        public SalesLT_SalesOrderDetail()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
