// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace SampleDAL
{
    // ProductModelProductDescription
    public class SalesLT_ProductModelProductDescription
    {
        public int ProductModelId { get; set; } // ProductModelID (Primary key)
        public int ProductDescriptionId { get; set; } // ProductDescriptionID (Primary key)
        public string Culture { get; set; } // Culture (Primary key) (length: 6)
        public Guid Rowguid { get; set; } // rowguid
        public DateTime ModifiedDate { get; set; } // ModifiedDate

        // Foreign keys

        /// <summary>
        /// Parent SalesLT_ProductDescription pointed by [ProductModelProductDescription].([ProductDescriptionId]) (FK_ProductModelProductDescription_ProductDescription_ProductDescriptionID)
        /// </summary>
        public SalesLT_ProductDescription SalesLT_ProductDescription { get; set; } // FK_ProductModelProductDescription_ProductDescription_ProductDescriptionID

        /// <summary>
        /// Parent SalesLT_ProductModel pointed by [ProductModelProductDescription].([ProductModelId]) (FK_ProductModelProductDescription_ProductModel_ProductModelID)
        /// </summary>
        public SalesLT_ProductModel SalesLT_ProductModel { get; set; } // FK_ProductModelProductDescription_ProductModel_ProductModelID

        public SalesLT_ProductModelProductDescription()
        {
            Rowguid = Guid.NewGuid();
            ModifiedDate = DateTime.Now;
        }
    }

}
// </auto-generated>
