// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace SampleDAL
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public class UfnGetAllCategoriesReturnModel
    {
        public string ParentProductCategoryName { get; set; }
        public string ProductCategoryName { get; set; }
        public int ProductCategoryID { get; set; }
    }

}
// </auto-generated>
