// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace SampleDAL
{
    public class UfnGetCustomerInformationReturnModel
    {
        public int CustomerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }

}
// </auto-generated>
