// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace SampleDAL
{
    // ProductCategory
    public partial class SalesLT_ProductCategoryConfiguration : IEntityTypeConfiguration<SalesLT_ProductCategory>
    {
        public void Configure(EntityTypeBuilder<SalesLT_ProductCategory> builder)
        {
            builder.ToTable("ProductCategory", "SalesLT");
            builder.HasKey(x => x.ProductCategoryId).HasName("PK_ProductCategory_ProductCategoryID").IsClustered();

            builder.Property(x => x.ProductCategoryId).HasColumnName(@"ProductCategoryID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.ParentProductCategoryId).HasColumnName(@"ParentProductCategoryID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.Rowguid).HasColumnName(@"rowguid").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.ParentProductCategory).WithMany(b => b.SalesLT_ProductCategories).HasForeignKey(c => c.ParentProductCategoryId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_ProductCategory_ProductCategory_ParentProductCategoryID_ProductCategoryID");

            builder.HasIndex(x => x.Name).HasDatabaseName("AK_ProductCategory_Name").IsUnique();
            builder.HasIndex(x => x.Rowguid).HasDatabaseName("AK_ProductCategory_rowguid").IsUnique();
            builder.HasIndex(x => x.ParentProductCategoryId).HasDatabaseName("IX_ProductCategory_ParentProductCategoryID");

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<SalesLT_ProductCategory> builder);
    }

}
// </auto-generated>
