// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace SampleDAL
{
    // ProductDescription
    public partial class SalesLT_ProductDescriptionConfiguration : IEntityTypeConfiguration<SalesLT_ProductDescription>
    {
        public void Configure(EntityTypeBuilder<SalesLT_ProductDescription> builder)
        {
            builder.ToTable("ProductDescription", "SalesLT");
            builder.HasKey(x => x.ProductDescriptionId).HasName("PK_ProductDescription_ProductDescriptionID").IsClustered();

            builder.Property(x => x.ProductDescriptionId).HasColumnName(@"ProductDescriptionID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar(400)").IsRequired().HasMaxLength(400);
            builder.Property(x => x.Rowguid).HasColumnName(@"rowguid").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            builder.HasIndex(x => x.Rowguid).HasDatabaseName("AK_ProductDescription_rowguid").IsUnique();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<SalesLT_ProductDescription> builder);
    }

}
// </auto-generated>
