// <auto-generated>
// ReSharper disable All

using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlTypes;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace SampleDAL
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public class MyDbContext : DbContext, IMyDbContext
    {
        public MyDbContext()
        {
        }

        public MyDbContext(DbContextOptions<MyDbContext> options)
            : base(options)
        {
        }

        public DbSet<SalesLT_Address> SalesLT_Addresses { get; set; } // Address
        public DbSet<SalesLT_Customer> SalesLT_Customers { get; set; } // Customer
        public DbSet<SalesLT_CustomerAddress> SalesLT_CustomerAddresses { get; set; } // CustomerAddress
        public DbSet<SalesLT_Product> SalesLT_Products { get; set; } // Product
        public DbSet<SalesLT_ProductCategory> SalesLT_ProductCategories { get; set; } // ProductCategory
        public DbSet<SalesLT_ProductDescription> SalesLT_ProductDescriptions { get; set; } // ProductDescription
        public DbSet<SalesLT_ProductModel> SalesLT_ProductModels { get; set; } // ProductModel
        public DbSet<SalesLT_ProductModelProductDescription> SalesLT_ProductModelProductDescriptions { get; set; } // ProductModelProductDescription
        public DbSet<SalesLT_SalesOrderDetail> SalesLT_SalesOrderDetails { get; set; } // SalesOrderDetail
        public DbSet<SalesLT_SalesOrderHeader> SalesLT_SalesOrderHeaders { get; set; } // SalesOrderHeader

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(@"Data Source=(LocalDb)\MSSQLLocalDB;Initial Catalog=aspnet-MvcMovie;Integrated Security=SSPI;AttachDBFilename=|DataDirectory|\Movies.mdf");
            }
        }

        public bool IsSqlParameterNull(SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == DBNull.Value);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.HasSequence<int>("SalesOrderNumber", "SalesLT").StartsAt(1).IncrementsBy(1).IsCyclic(false);

            modelBuilder.ApplyConfiguration(new SalesLT_AddressConfiguration());
            modelBuilder.ApplyConfiguration(new SalesLT_CustomerConfiguration());
            modelBuilder.ApplyConfiguration(new SalesLT_CustomerAddressConfiguration());
            modelBuilder.ApplyConfiguration(new SalesLT_ProductConfiguration());
            modelBuilder.ApplyConfiguration(new SalesLT_ProductCategoryConfiguration());
            modelBuilder.ApplyConfiguration(new SalesLT_ProductDescriptionConfiguration());
            modelBuilder.ApplyConfiguration(new SalesLT_ProductModelConfiguration());
            modelBuilder.ApplyConfiguration(new SalesLT_ProductModelProductDescriptionConfiguration());
            modelBuilder.ApplyConfiguration(new SalesLT_SalesOrderDetailConfiguration());
            modelBuilder.ApplyConfiguration(new SalesLT_SalesOrderHeaderConfiguration());

            modelBuilder.Entity<SalesLT_SalesOrderDetail>().ToTable(tb => tb.HasTrigger("HasComputedColumn"));
            modelBuilder.Entity<SalesLT_SalesOrderHeader>().ToTable(tb => tb.HasTrigger("HasComputedColumn"));

        }


        // Stored Procedures
        public int UspLogError(out int? errorLogId)
        {
            var errorLogIdParam = new SqlParameter { ParameterName = "@ErrorLogID", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output, Precision = 10, Scale = 0 };
            var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };

            Database.ExecuteSqlRaw("EXEC @procResult = [dbo].[uspLogError] @ErrorLogID OUTPUT", errorLogIdParam, procResultParam);

            if (IsSqlParameterNull(errorLogIdParam))
                errorLogId = null;
            else
                errorLogId = (int) errorLogIdParam.Value;

            return (int)procResultParam.Value;
        }

        // UspLogErrorAsync() cannot be created due to having out parameters, or is relying on the procedure result (int)

        public int UspPrintError()
        {
            var procResultParam = new SqlParameter { ParameterName = "@procResult", SqlDbType = SqlDbType.Int, Direction = ParameterDirection.Output };

            Database.ExecuteSqlRaw("EXEC @procResult = [dbo].[uspPrintError] ", procResultParam);

            return (int)procResultParam.Value;
        }

        // UspPrintErrorAsync() cannot be created due to having out parameters, or is relying on the procedure result (int)

    }
}
// </auto-generated>
